// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v12220522cambios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v12220522cambios));
        
        string IMigrationMetadata.Id
        {
            get { return "202205220615409_v1.2-220522-cambios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
